name: utils
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^11.1.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  dio: ^5.9.1
  dart_either: ^2.0.0
  copy_with_extension: ^11.0.0
  json_annotation: ^4.9.0
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.4
  excel_plus: ^1.1.0
  file_selector: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  auto_route_generator: ^10.4.0
  injectable_generator: ^2.12.0
  copy_with_extension_gen: ^11.0.0
  json_serializable: ^6.11.4
  build_runner: ^2.11.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - l10n/
